export const COPY = {
  en: {
    header: {
      login: "Login",
      register: "Register",
    },
    hero: {
      badge: "Broadcast daily · Manila",
      titleLead: "Where the pit",
      titleAccent: "meets the pulse.",
      body:
        "Original live feeds. Self-service transactions. GCash, Maya, QRPH — all in one platform. A premium experience built for sabong fans who demand more.",
      cta: "Step into the ring",
      alt: "Live sabong arena",
    },
    marquee: [
      "LIVE ACTION",
      "REAL PASSION",
      "PREMIUM E-SABONG",
      "RINGSIDE FROM ANYWHERE",
      "ONE COMMUNITY",
      "BROADCAST DAILY",
      "ALOPIT",
      "MAS SIMPLE",
      "MAS CONVENIENT",
      "ORIGINAL LIVE FEED",
    ],
    trust: [
      {
        title: "Safe & secure",
        body: "Trusted room entry and reliable system.",
      },
      {
        title: "Self cash-in & out",
        body: "Fast deposits and withdrawals on your terms.",
      },
      {
        title: "Mobile-first",
        body: "Designed for phones, scaled up cleanly.",
      },
      {
        title: "Live support",
        body: "Help is close when you need it most.",
        liveChat: true,
      },
    ],
    promo: {
      ariaPrefix: "Show promotion",
    },
    why: {
      eyebrow: "Why Alopit",
      titleLead: "Built for sabong fans,",
      titleAccent: "end to end.",
      body: "Original feeds, smooth viewing, self-service transactions — everything you need in one platform.",
      roomState: "Live now",
      roomTitle: "Sabong Traditional",
      featureLabel: "Feature",
      features: [
        "Original live feed",
        "Self-service transactions",
        "Multiple payment channels",
        "Smooth viewing",
        "Exclusive community",
      ],
      featureBodies: [
        "Crystal-clear HD streams with low latency. Not all live viewing is created equal.",
        "Cash in and cash out anytime — no manual process, no waiting.",
        "GCash, Maya, and QRPH-supported banks all in one platform.",
        "A dedicated platform environment built for uninterrupted streaming.",
        "Invite players, grow your network, and unlock more rewards together.",
      ],
    },
    payments: {
      eyebrow: "Convenience Matters",
      titleLead: "Self-service",
      titleAccent: "transactions.",
      body: "Smooth deposits, fast withdrawals, wallets, QR rails, bank channels, and crypto options — all in one reliable platform. No manual process, no waiting.",
      supported: "Supported",
      currencies: "Supported currencies",
      currencyCodes: ["PHP", "THB", "VND", "MYR", "MXN", "INR", "USDT"],
      statusLabels: ["Self Cash-In", "Self Cash-Out", "Fast Processing"],
      paymentBodies: [
        "Instant cash-in and cash-out via GCash wallet.",
        "Seamless transactions with Maya support.",
        "Supported bank transfers via QRPH nationwide.",
      ],
    },
    affiliate: {
      eyebrow: "Affiliate Partner Program",
      titleLead: "Grow your network,",
      titleAccent: "earn real commissions.",
      body: "Become an Alopit affiliate and earn commissions from downline betting turnover across Sabong Arena. Turnover-based commissions — your network, your earnings.",
      tiers: [
        {
          tierLabel: "Gold",
          badge: "Recommended",
          commission: "3%",
          maxLabel: "max commission rate",
          createdBy: "Master affiliate only",
          features: [
            "Turnover-based commissions",
            "Separate commission wallet",
            "Transfer-to-balance anytime",
            "Create Silver & Bronze affiliates",
            "Full deposit/withdraw to downlines",
          ],
        },
        {
          tierLabel: "Silver",
          badge: null,
          commission: "2%",
          maxLabel: "max commission rate",
          createdBy: "Gold or Master affiliate",
          features: [
            "Turnover-based commissions",
            "Separate commission wallet",
            "Transfer-to-balance anytime",
            "Create Bronze affiliates",
            "Deposit/Withdraw to downlines",
          ],
        },
        {
          tierLabel: "Bronze",
          badge: null,
          commission: "1%",
          maxLabel: "max commission rate",
          createdBy: "Gold, Silver, or Master affiliate",
          features: [
            "Turnover-based commissions",
            "Separate commission wallet",
            "Transfer-to-balance anytime",
            "Can create downline affiliates",
            "Deposit/Withdraw to downlines",
          ],
        },
      ],
      hierarchyEyebrow: "Recruitment Hierarchy",
      hierarchyNote: "Each tier can recruit and manage affiliates below them in the chain",
      createdByLabel: "Created by:",
      cta: "Become an Affiliate",
    },
    beyond: {
      eyebrow: "Beyond Sabong",
      titleLead: "Like Alopit?",
      titleAccent: "Try Alowin.",
      body: "World-class slots, live casino, and game shows — all on one platform. Same trusted experience, unlimited entertainment.",
      categories: ["All", "Casino", "Live Casino", "Games"],
      cta: "Explore all games on Alowin",
      footer: "Slots · Live Casino · Table Games · Game Shows",
    },
    sportsbook: {
      eyebrow: "Sportsbook",
      titleLead: "Alowin",
      titleAccent: "Sportsbook.",
      body: "Move between live sports and pre-match action across football, basketball, tennis, and more with the same Alowin account experience.",
      tags: ["Live sports", "Pre-match", "Multi-sport"],
      boardEyebrow: "Sportsbook board",
      boardTitle: "Live and pre-match",
      modes: [
        {
          mode: "Live",
          title: "Follow the action as it happens",
          body: "Jump into active games and keep the matchday energy moving inside the Alowin sportsbook experience.",
          cta: "Open live sports",
        },
        {
          mode: "Pre-match",
          title: "Plan before kickoff",
          body: "Browse upcoming fixtures, choose your sport, and enter before the game starts.",
          cta: "View pre-match sports",
        },
      ],
      flowEyebrow: "One sportsbook flow",
      flowBody: "Start with upcoming matches, switch into live events, and continue straight into Alowin when you are ready.",
      cta: "Open Sportsbook",
    },
    final: {
      eyebrow: "Join today",
      titleLead: "Welcome to the",
      titleAccent: "Alopit community.",
      body: "Where convenience meets community. Self-service transactions, premium streams, and exclusive access — all in one platform.",
      cta: "Enter the arena",
      note: "Free · Web · No download",
    },
    footer: {
      brand: "Alopit",
      copyright: "© 2026 Alopit",
      responsible: "Play responsibly · 21+",
    },
  },
  th: {
    header: {
      login: "เข้าสู่ระบบ",
      register: "สมัครสมาชิก",
    },
    hero: {
      badge: "ถ่ายทอดสดทุกวัน · มะนิลา",
      titleLead: "สนามจริง",
      titleAccent: "กับจังหวะที่ชัดเจน.",
      body:
        "ถ่ายทอดสดต้นฉบับ ธุรกรรมด้วยตนเอง รองรับ GCash, Maya, QRPH — ทุกอย่างอยู่ในแพลตฟอร์มเดียว ประสบการณ์พรีเมียมที่สร้างมาเพื่อแฟนซาบองที่ต้องการมากกว่าเดิม",
      cta: "เข้าสู่สนาม",
      alt: "สนามซาบองแบบสด",
    },
    marquee: [
      "แอ็กชันสด",
      "แพสชันจริง",
      "อีซาบองพรีเมียม",
      "รับชมได้ทุกที่",
      "ชุมชนเดียวกัน",
      "ถ่ายทอดสดทุกวัน",
      "ALOPIT",
      "ง่ายกว่าเดิม",
      "สะดวกกว่าเดิม",
      "ฟีดสดต้นฉบับ",
    ],
    trust: [
      {
        title: "ปลอดภัยและเชื่อถือได้",
        body: "เข้าใช้งานห้องที่ไว้ใจได้และระบบที่เสถียร",
      },
      {
        title: "ฝาก-ถอนด้วยตัวเอง",
        body: "ฝากและถอนรวดเร็วตามจังหวะของคุณ",
      },
      {
        title: "ออกแบบเพื่อมือถือ",
        body: "ใช้งานบนโทรศัพท์ได้ดี และขยายจอได้สวยงาม",
      },
      {
        title: "ซัพพอร์ตสด",
        body: "มีคนช่วยเหลือใกล้ตัวเมื่อคุณต้องการ",
        liveChat: true,
      },
    ],
    promo: {
      ariaPrefix: "แสดงโปรโมชัน",
    },
    why: {
      eyebrow: "ทำไมต้อง Alopit",
      titleLead: "สร้างมาเพื่อแฟนซาบอง",
      titleAccent: "ครบจบในที่เดียว",
      body: "ฟีดต้นฉบับ การรับชมลื่นไหล และธุรกรรมด้วยตนเอง ทุกอย่างที่ต้องใช้รวมอยู่ในแพลตฟอร์มเดียว",
      roomState: "กำลังถ่ายทอดสด",
      roomTitle: "Sabong Traditional",
      featureLabel: "ฟีเจอร์",
      features: [
        "ฟีดสดต้นฉบับ",
        "ธุรกรรมด้วยตนเอง",
        "หลายช่องทางการชำระเงิน",
        "การรับชมที่ลื่นไหล",
        "ชุมชนพิเศษเฉพาะสมาชิก",
      ],
      featureBodies: [
        "สตรีม HD คมชัดและหน่วงต่ำ การรับชมสดที่ดีต้องต่างจากที่อื่น",
        "ฝากและถอนเมื่อไหร่ก็ได้ ไม่ต้องผ่านขั้นตอนแมนนวล ไม่ต้องรอ",
        "รวม GCash, Maya และธนาคารที่รองรับ QRPH ไว้ในที่เดียว",
        "แพลตฟอร์มที่ออกแบบมาเพื่อการสตรีมต่อเนื่องแบบไม่สะดุด",
        "ชวนผู้เล่น เพิ่มเครือข่าย และปลดล็อกผลตอบแทนได้มากขึ้น",
      ],
    },
    payments: {
      eyebrow: "ความสะดวกคือเรื่องสำคัญ",
      titleLead: "ธุรกรรม",
      titleAccent: "ด้วยตนเอง",
      body: "ฝากง่าย ถอนเร็ว รองรับวอลเล็ต QR ธนาคาร และคริปโต — ทั้งหมดอยู่ในแพลตฟอร์มเดียวที่เชื่อถือได้ ไม่ต้องรอ ไม่ต้องใช้ขั้นตอนยุ่งยาก",
      supported: "รองรับ",
      currencies: "Supported currencies",
      currencyCodes: ["PHP", "THB", "VND", "MYR", "MXN", "INR", "USDT"],
      statusLabels: ["ฝากเอง", "ถอนเอง", "ประมวลผลเร็ว"],
      paymentBodies: [
        "ฝากและถอนทันทีผ่านกระเป๋า GCash",
        "ทำรายการได้ลื่นไหลด้วยการรองรับ Maya",
        "รองรับการโอนธนาคารผ่าน QRPH ทั่วประเทศ",
      ],
    },
    affiliate: {
      eyebrow: "โปรแกรมพันธมิตร",
      titleLead: "ขยายเครือข่ายของคุณ",
      titleAccent: "รับคอมมิชชันจริง",
      body: "สมัครเป็นพันธมิตร Alopit และรับคอมมิชชันจากยอดเดิมพันของทีมย่อยทั่ว Sabong Arena คิดจากยอดหมุนเวียน เครือข่ายของคุณคือรายได้ของคุณ",
      tiers: [
        {
          tierLabel: "Gold",
          badge: "แนะนำ",
          commission: "3%",
          maxLabel: "อัตราคอมมิชชันสูงสุด",
          createdBy: "เฉพาะ Master affiliate",
          features: [
            "คอมมิชชันคิดจากยอดหมุนเวียน",
            "กระเป๋าคอมมิชชันแยกต่างหาก",
            "โอนเข้ายอดหลักได้ตลอดเวลา",
            "สร้างพันธมิตรระดับ Silver และ Bronze",
            "ฝาก/ถอนถึงทีมย่อยได้เต็มรูปแบบ",
          ],
        },
        {
          tierLabel: "Silver",
          badge: null,
          commission: "2%",
          maxLabel: "อัตราคอมมิชชันสูงสุด",
          createdBy: "Gold หรือ Master affiliate",
          features: [
            "คอมมิชชันคิดจากยอดหมุนเวียน",
            "กระเป๋าคอมมิชชันแยกต่างหาก",
            "โอนเข้ายอดหลักได้ตลอดเวลา",
            "สร้างพันธมิตรระดับ Bronze",
            "ฝาก/ถอนถึงทีมย่อยได้",
          ],
        },
        {
          tierLabel: "Bronze",
          badge: null,
          commission: "1%",
          maxLabel: "อัตราคอมมิชชันสูงสุด",
          createdBy: "Gold, Silver หรือ Master affiliate",
          features: [
            "คอมมิชชันคิดจากยอดหมุนเวียน",
            "กระเป๋าคอมมิชชันแยกต่างหาก",
            "โอนเข้ายอดหลักได้ตลอดเวลา",
            "สามารถสร้างพันธมิตรย่อยได้",
            "ฝาก/ถอนถึงทีมย่อยได้",
          ],
        },
      ],
      hierarchyEyebrow: "ลำดับการรับสมัคร",
      hierarchyNote: "แต่ละระดับสามารถรับสมัครและดูแลพันธมิตรระดับถัดลงไปได้",
      createdByLabel: "สร้างโดย:",
      cta: "สมัครเป็นพันธมิตร",
    },
    beyond: {
      eyebrow: "ต่อจากซาบอง",
      titleLead: "ชอบ Alopit ไหม",
      titleAccent: "ลอง Alowin.",
      body: "สล็อตระดับโลก ไลฟ์คาสิโน และเกมโชว์ — รวมอยู่ในแพลตฟอร์มเดียว ประสบการณ์เชื่อถือได้เหมือนเดิม แต่ความบันเทิงไม่จำกัด",
      categories: ["ทั้งหมด", "คาสิโน", "ไลฟ์คาสิโน", "เกม"],
      cta: "ดูเกมทั้งหมดบน Alowin",
      footer: "สล็อต · ไลฟ์คาสิโน · เกมโต๊ะ · เกมโชว์",
    },
    sportsbook: {
      eyebrow: "สปอร์ตบุ๊ก",
      titleLead: "Alowin",
      titleAccent: "Sportsbook.",
      body: "สลับระหว่างกีฬาแบบสดและก่อนแข่งได้อย่างราบรื่น ครอบคลุมฟุตบอล บาสเกตบอล เทนนิส และอีกมากมาย ด้วยประสบการณ์บัญชี Alowin เดิม",
      tags: ["กีฬาแบบสด", "ก่อนแข่ง", "หลายกีฬา"],
      boardEyebrow: "บอร์ดสปอร์ตบุ๊ก",
      boardTitle: "สดและก่อนแข่ง",
      modes: [
        {
          mode: "สด",
          title: "ตามเกมให้ทันทุกจังหวะ",
          body: "เข้าสู่เกมที่กำลังเกิดขึ้นและรักษาโมเมนตัมของวันแข่งขันไว้ในประสบการณ์สปอร์ตบุ๊กของ Alowin",
          cta: "เปิดกีฬาแบบสด",
        },
        {
          mode: "ก่อนแข่ง",
          title: "วางแผนก่อนเริ่ม",
          body: "ดูรายการแข่งขันที่กำลังจะมาถึง เลือกกีฬา และเข้าเล่นก่อนเกมเริ่ม",
          cta: "ดูสปอร์ตก่อนแข่ง",
        },
      ],
      flowEyebrow: "เส้นทางสปอร์ตบุ๊กเดียว",
      flowBody: "เริ่มจากแมตช์ที่กำลังจะเริ่ม สลับไปยังอีเวนต์สด และเข้าสู่ Alowin ต่อได้ทันทีเมื่อพร้อม",
      cta: "เปิด Sportsbook",
    },
    final: {
      eyebrow: "เข้าร่วมวันนี้",
      titleLead: "ยินดีต้อนรับสู่",
      titleAccent: "คอมมูนิตี้ Alopit",
      body: "ที่ซึ่งความสะดวกมาพร้อมกับชุมชน ธุรกรรมด้วยตนเอง สตรีมคุณภาพสูง และสิทธิ์เข้าถึงพิเศษ — รวมอยู่ในแพลตฟอร์มเดียว",
      cta: "เข้าสู่สนาม",
      note: "ฟรี · เว็บ · ไม่ต้องดาวน์โหลด",
    },
    footer: {
      brand: "Alopit",
      copyright: "© 2026 Alopit",
      responsible: "เล่นอย่างรับผิดชอบ · 21+",
    },
  },
  ms: {
    header: {
      login: "Log masuk",
      register: "Daftar",
    },
    hero: {
      badge: "Siaran harian · Manila",
      titleLead: "Di mana arena",
      titleAccent: "bertemu nadi.",
      body:
        "Siaran langsung asli. Transaksi layan diri. GCash, Maya, QRPH — semuanya dalam satu platform. Pengalaman premium yang dibina untuk peminat sabong yang mahukan lebih.",
      cta: "Masuk ke gelanggang",
      alt: "Arena sabong langsung",
    },
    marquee: [
      "AKSI LANGSUNG",
      "SEMANGAT SEBENAR",
      "E-SABONG PREMIUM",
      "DARI MANA SAJA",
      "SATU KOMUNITI",
      "SIARAN HARIAN",
      "ALOPIT",
      "LEBIH MUDAH",
      "LEBIH SELESA",
      "SIARAN LANGSUNG ASAL",
    ],
    trust: [
      {
        title: "Selamat & terjamin",
        body: "Kemasukan bilik yang dipercayai dan sistem yang boleh diharap.",
      },
      {
        title: "Deposit & pengeluaran layan diri",
        body: "Deposit dan pengeluaran pantas mengikut pilihan anda.",
      },
      {
        title: "Utama untuk mudah alih",
        body: "Direka untuk telefon dan diskalakan dengan kemas.",
      },
      {
        title: "Sokongan langsung",
        body: "Bantuan sentiasa dekat apabila anda paling memerlukannya.",
        liveChat: true,
      },
    ],
    promo: {
      ariaPrefix: "Tunjuk promosi",
    },
    why: {
      eyebrow: "Mengapa Alopit",
      titleLead: "Dibina untuk peminat sabong,",
      titleAccent: "dari hujung ke hujung.",
      body: "Siaran asal, tontonan lancar, transaksi layan diri — semua yang anda perlukan dalam satu platform.",
      roomState: "Sedang langsung",
      roomTitle: "Sabong Traditional",
      featureLabel: "Ciri",
      features: [
        "Siaran langsung asal",
        "Transaksi layan diri",
        "Pelbagai saluran pembayaran",
        "Tontonan lancar",
        "Komuniti eksklusif",
      ],
      featureBodies: [
        "Siaran HD yang jelas dengan kependaman rendah. Bukan semua tontonan langsung sama.",
        "Deposit dan keluarkan dana bila-bila masa — tanpa proses manual, tanpa menunggu.",
        "GCash, Maya, dan bank yang disokong QRPH semuanya dalam satu platform.",
        "Persekitaran platform khusus yang dibina untuk penstriman tanpa gangguan.",
        "Jemput pemain, besarkan rangkaian anda, dan buka lebih banyak ganjaran bersama.",
      ],
    },
    payments: {
      eyebrow: "Kemudahan itu penting",
      titleLead: "Transaksi",
      titleAccent: "layan diri.",
      body: "Deposit lancar, pengeluaran pantas, dompet, QR, saluran bank, dan pilihan kripto — semuanya dalam satu platform yang boleh dipercayai. Tiada proses manual, tiada menunggu.",
      supported: "Disokong",
      currencies: "Supported currencies",
      currencyCodes: ["PHP", "THB", "VND", "MYR", "MXN", "INR", "USDT"],
      statusLabels: ["Deposit Layan Diri", "Pengeluaran Layan Diri", "Pemprosesan Pantas"],
      paymentBodies: [
        "Deposit dan keluarkan dana segera melalui dompet GCash.",
        "Transaksi lancar dengan sokongan Maya.",
        "Pemindahan bank melalui QRPH disokong di seluruh negara.",
      ],
    },
    affiliate: {
      eyebrow: "Program Rakan Sekutu",
      titleLead: "Kembangkan rangkaian anda,",
      titleAccent: "raih komisen sebenar.",
      body: "Sertai sebagai rakan sekutu Alopit dan dapatkan komisen daripada turnover pertaruhan downline di seluruh Sabong Arena. Komisen berasaskan turnover — rangkaian anda, pendapatan anda.",
      tiers: [
        {
          tierLabel: "Gold",
          badge: "Disyorkan",
          commission: "3%",
          maxLabel: "kadar komisen maksimum",
          createdBy: "Hanya untuk Master affiliate",
          features: [
            "Komisen berasaskan turnover",
            "Dompet komisen berasingan",
            "Pindah ke baki bila-bila masa",
            "Buat rakan sekutu Silver & Bronze",
            "Deposit/pengeluaran penuh kepada downline",
          ],
        },
        {
          tierLabel: "Silver",
          badge: null,
          commission: "2%",
          maxLabel: "kadar komisen maksimum",
          createdBy: "Gold atau Master affiliate",
          features: [
            "Komisen berasaskan turnover",
            "Dompet komisen berasingan",
            "Pindah ke baki bila-bila masa",
            "Buat rakan sekutu Bronze",
            "Deposit/pengeluaran kepada downline",
          ],
        },
        {
          tierLabel: "Bronze",
          badge: null,
          commission: "1%",
          maxLabel: "kadar komisen maksimum",
          createdBy: "Gold, Silver, atau Master affiliate",
          features: [
            "Komisen berasaskan turnover",
            "Dompet komisen berasingan",
            "Pindah ke baki bila-bila masa",
            "Boleh buat rakan sekutu downline",
            "Deposit/pengeluaran kepada downline",
          ],
        },
      ],
      hierarchyEyebrow: "Hierarki Pengambilan",
      hierarchyNote: "Setiap tier boleh merekrut dan mengurus rakan sekutu di bawah mereka dalam rantaian",
      createdByLabel: "Dicipta oleh:",
      cta: "Jadi Rakan Sekutu",
    },
    beyond: {
      eyebrow: "Di luar Sabong",
      titleLead: "Suka Alopit?",
      titleAccent: "Cuba Alowin.",
      body: "Slot bertaraf dunia, kasino langsung, dan rancangan permainan — semuanya dalam satu platform. Pengalaman yang sama dipercayai, hiburan tanpa had.",
      categories: ["Semua", "Kasino", "Kasino Langsung", "Permainan"],
      cta: "Terokai semua permainan di Alowin",
      footer: "Slot · Kasino Langsung · Permainan Meja · Rancangan Permainan",
    },
    sportsbook: {
      eyebrow: "Sportsbook",
      titleLead: "Alowin",
      titleAccent: "Sportsbook.",
      body: "Beralih antara sukan langsung dan aksi sebelum perlawanan merentas bola sepak, bola keranjang, tenis, dan banyak lagi dengan pengalaman akaun Alowin yang sama.",
      tags: ["Sukan langsung", "Pra-perlawanan", "Pelbagai sukan"],
      boardEyebrow: "Papan sportsbook",
      boardTitle: "Langsung dan pra-perlawanan",
      modes: [
        {
          mode: "Langsung",
          title: "Ikuti aksi ketika ia berlaku",
          body: "Masuk ke permainan aktif dan kekalkan tenaga hari perlawanan dalam pengalaman sportsbook Alowin.",
          cta: "Buka sukan langsung",
        },
        {
          mode: "Pra-perlawanan",
          title: "Rancang sebelum sepak mula",
          body: "Semak perlawanan akan datang, pilih sukan anda, dan masuk sebelum permainan bermula.",
          cta: "Lihat sukan pra-perlawanan",
        },
      ],
      flowEyebrow: "Satu aliran sportsbook",
      flowBody: "Mula dengan perlawanan akan datang, beralih ke acara langsung, dan teruskan ke Alowin apabila anda bersedia.",
      cta: "Buka Sportsbook",
    },
    final: {
      eyebrow: "Sertai hari ini",
      titleLead: "Selamat datang ke",
      titleAccent: "komuniti Alopit.",
      body: "Di mana kemudahan bertemu komuniti. Transaksi layan diri, siaran premium, dan akses eksklusif — semuanya dalam satu platform.",
      cta: "Masuk ke arena",
      note: "Percuma · Web · Tiada muat turun",
    },
    footer: {
      brand: "Alopit",
      copyright: "© 2026 Alopit",
      responsible: "Main dengan bertanggungjawab · 21+",
    },
  },
  id: {
    header: {
      login: "Masuk",
      register: "Daftar",
    },
    hero: {
      badge: "Siaran harian · Manila",
      titleLead: "Saat arena",
      titleAccent: "bertemu denyut.",
      body:
        "Siaran langsung asli. Transaksi mandiri. GCash, Maya, QRPH — semuanya dalam satu platform. Pengalaman premium yang dibuat untuk penggemar sabong yang menginginkan lebih.",
      cta: "Masuk ke arena",
      alt: "Arena sabong langsung",
    },
    marquee: [
      "AKSI LANGSUNG",
      "SEMANGAT ASLI",
      "E-SABONG PREMIUM",
      "DARI MANA SAJA",
      "SATU KOMUNITAS",
      "SIARAN HARIAN",
      "ALOPIT",
      "LEBIH SEDERHANA",
      "LEBIH PRAKTIS",
      "SIARAN LANGSUNG ASLI",
    ],
    trust: [
      {
        title: "Aman & terlindungi",
        body: "Masuk ke room yang tepercaya dan sistem yang andal.",
      },
      {
        title: "Setor & tarik mandiri",
        body: "Deposit dan penarikan cepat sesuai kebutuhan Anda.",
      },
      {
        title: "Mobile-first",
        body: "Dirancang untuk ponsel, tetap rapi saat diperbesar.",
      },
      {
        title: "Dukungan langsung",
        body: "Bantuan dekat saat Anda paling membutuhkannya.",
        liveChat: true,
      },
    ],
    promo: {
      ariaPrefix: "Tampilkan promo",
    },
    why: {
      eyebrow: "Mengapa Alopit",
      titleLead: "Dibuat untuk penggemar sabong,",
      titleAccent: "dari awal sampai akhir.",
      body: "Siaran asli, pengalaman menonton mulus, transaksi mandiri — semua yang Anda butuhkan dalam satu platform.",
      roomState: "Sedang live",
      roomTitle: "Sabong Traditional",
      featureLabel: "Fitur",
      features: [
        "Siaran langsung asli",
        "Transaksi mandiri",
        "Berbagai saluran pembayaran",
        "Pengalaman menonton mulus",
        "Komunitas eksklusif",
      ],
      featureBodies: [
        "Streaming HD jernih dengan latensi rendah. Tidak semua tayangan live setara.",
        "Isi dan tarik dana kapan saja — tanpa proses manual, tanpa menunggu.",
        "GCash, Maya, dan bank yang didukung QRPH dalam satu platform.",
        "Lingkungan platform khusus yang dibangun untuk streaming tanpa gangguan.",
        "Undang pemain, kembangkan jaringan Anda, dan buka lebih banyak reward bersama.",
      ],
    },
    payments: {
      eyebrow: "Kemudahan itu penting",
      titleLead: "Transaksi",
      titleAccent: "mandiri.",
      body: "Deposit lancar, penarikan cepat, dompet, QR, kanal bank, dan opsi kripto — semuanya dalam satu platform yang andal. Tanpa proses manual, tanpa menunggu.",
      supported: "Didukung",
      currencies: "Supported currencies",
      currencyCodes: ["PHP", "THB", "VND", "MYR", "MXN", "INR", "USDT"],
      statusLabels: ["Setor Mandiri", "Tarik Mandiri", "Pemrosesan Cepat"],
      paymentBodies: [
        "Setor dan tarik dana instan melalui dompet GCash.",
        "Transaksi lancar dengan dukungan Maya.",
        "Transfer bank yang didukung QRPH di seluruh negeri.",
      ],
    },
    affiliate: {
      eyebrow: "Program Mitra Afiliasi",
      titleLead: "Kembangkan jaringan Anda,",
      titleAccent: "dapatkan komisi nyata.",
      body: "Jadi afiliasi Alopit dan dapatkan komisi dari turnover taruhan downline di seluruh Sabong Arena. Komisi berbasis turnover — jaringan Anda, penghasilan Anda.",
      tiers: [
        {
          tierLabel: "Gold",
          badge: "Direkomendasikan",
          commission: "3%",
          maxLabel: "tarif komisi maksimum",
          createdBy: "Hanya affiliate Master",
          features: [
            "Komisi berbasis turnover",
            "Dompet komisi terpisah",
            "Transfer ke saldo kapan saja",
            "Buat affiliate Silver & Bronze",
            "Deposit/withdraw penuh ke downline",
          ],
        },
        {
          tierLabel: "Silver",
          badge: null,
          commission: "2%",
          maxLabel: "tarif komisi maksimum",
          createdBy: "Gold atau affiliate Master",
          features: [
            "Komisi berbasis turnover",
            "Dompet komisi terpisah",
            "Transfer ke saldo kapan saja",
            "Buat affiliate Bronze",
            "Deposit/withdraw ke downline",
          ],
        },
        {
          tierLabel: "Bronze",
          badge: null,
          commission: "1%",
          maxLabel: "tarif komisi maksimum",
          createdBy: "Gold, Silver, atau affiliate Master",
          features: [
            "Komisi berbasis turnover",
            "Dompet komisi terpisah",
            "Transfer ke saldo kapan saja",
            "Bisa membuat affiliate downline",
            "Deposit/withdraw ke downline",
          ],
        },
      ],
      hierarchyEyebrow: "Hierarki rekrutmen",
      hierarchyNote: "Setiap tier dapat merekrut dan mengelola affiliate di bawahnya dalam rantai",
      createdByLabel: "Dibuat oleh:",
      cta: "Jadi Affiliate",
    },
    beyond: {
      eyebrow: "Di luar Sabong",
      titleLead: "Suka Alopit?",
      titleAccent: "Coba Alowin.",
      body: "Slot kelas dunia, live casino, dan game show — semuanya dalam satu platform. Pengalaman tepercaya yang sama, hiburan tanpa batas.",
      categories: ["Semua", "Casino", "Live Casino", "Game"],
      cta: "Jelajahi semua game di Alowin",
      footer: "Slot · Live Casino · Table Games · Game Show",
    },
    sportsbook: {
      eyebrow: "Sportsbook",
      titleLead: "Alowin",
      titleAccent: "Sportsbook.",
      body: "Pindah antara olahraga live dan pra-pertandingan untuk sepak bola, basket, tenis, dan lainnya dengan pengalaman akun Alowin yang sama.",
      tags: ["Olahraga live", "Pra-pertandingan", "Multi-olahraga"],
      boardEyebrow: "Papan sportsbook",
      boardTitle: "Live dan pra-pertandingan",
      modes: [
        {
          mode: "Live",
          title: "Ikuti aksi saat terjadi",
          body: "Masuk ke pertandingan aktif dan jaga energi hari pertandingan tetap berjalan di pengalaman sportsbook Alowin.",
          cta: "Buka olahraga live",
        },
        {
          mode: "Pra-pertandingan",
          title: "Rencanakan sebelum kick-off",
          body: "Lihat pertandingan mendatang, pilih olahraga Anda, dan masuk sebelum permainan dimulai.",
          cta: "Lihat olahraga pra-pertandingan",
        },
      ],
      flowEyebrow: "Satu alur sportsbook",
      flowBody: "Mulai dari pertandingan mendatang, pindah ke event live, lalu lanjut langsung ke Alowin saat Anda siap.",
      cta: "Buka Sportsbook",
    },
    final: {
      eyebrow: "Gabung hari ini",
      titleLead: "Selamat datang di",
      titleAccent: "komunitas Alopit.",
      body: "Tempat kemudahan bertemu komunitas. Transaksi mandiri, streaming premium, dan akses eksklusif — semuanya dalam satu platform.",
      cta: "Masuk ke arena",
      note: "Gratis · Web · Tanpa unduhan",
    },
    footer: {
      brand: "Alopit",
      copyright: "© 2026 Alopit",
      responsible: "Bermain secara bertanggung jawab · 21+",
    },
  },
  vi: {
    header: {
      login: "Đăng nhập",
      register: "Đăng ký",
    },
    hero: {
      badge: "Phát sóng hằng ngày · Manila",
      titleLead: "Nơi sàn đấu",
      titleAccent: "gặp nhịp đập.",
      body:
        "Luồng trực tiếp gốc. Giao dịch tự phục vụ. GCash, Maya, QRPH — tất cả trong một nền tảng. Trải nghiệm cao cấp dành cho người hâm mộ sabong muốn nhiều hơn.",
      cta: "Bước vào sàn đấu",
      alt: "Sân sabong trực tiếp",
    },
    marquee: [
      "HÀNH ĐỘNG TRỰC TIẾP",
      "ĐAM MÊ THẬT",
      "E-SABONG CAO CẤP",
      "XEM Ở BẤT CỨ ĐÂU",
      "MỘT CỘNG ĐỒNG",
      "PHÁT SÓNG HẰNG NGÀY",
      "ALOPIT",
      "ĐƠN GIẢN HƠN",
      "TIỆN HƠN",
      "LUỒNG TRỰC TIẾP GỐC",
    ],
    trust: [
      {
        title: "An toàn & bảo mật",
        body: "Lối vào phòng đáng tin cậy và hệ thống ổn định.",
      },
      {
        title: "Tự nạp & rút",
        body: "Nạp và rút nhanh theo cách của bạn.",
      },
      {
        title: "Ưu tiên di động",
        body: "Thiết kế tối ưu cho điện thoại, mở rộng vẫn gọn.",
      },
      {
        title: "Hỗ trợ trực tiếp",
        body: "Luôn có người hỗ trợ khi bạn cần nhất.",
        liveChat: true,
      },
    ],
    promo: {
      ariaPrefix: "Hiển thị khuyến mãi",
    },
    why: {
      eyebrow: "Vì sao chọn Alopit",
      titleLead: "Được xây dựng cho người hâm mộ sabong,",
      titleAccent: "từ đầu đến cuối.",
      body: "Luồng gốc, xem mượt, giao dịch tự phục vụ — mọi thứ bạn cần trong một nền tảng.",
      roomState: "Đang live",
      roomTitle: "Sabong Traditional",
      featureLabel: "Tính năng",
      features: [
        "Luồng trực tiếp gốc",
        "Giao dịch tự phục vụ",
        "Nhiều kênh thanh toán",
        "Xem mượt mà",
        "Cộng đồng độc quyền",
      ],
      featureBodies: [
        "Luồng HD trong trẻo với độ trễ thấp. Không phải xem trực tiếp nào cũng như nhau.",
        "Nạp và rút bất cứ lúc nào - không thủ công, không chờ đợi.",
        "GCash, Maya và các ngân hàng hỗ trợ QRPH trong cùng một nền tảng.",
        "Môi trường nền tảng chuyên biệt được xây dựng cho phát trực tuyến liên tục.",
        "Mời người chơi, mở rộng mạng lưới và cùng nhau mở khóa nhiều phần thưởng hơn.",
      ],
    },
    payments: {
      eyebrow: "Sự tiện lợi rất quan trọng",
      titleLead: "Giao dịch",
      titleAccent: "tự phục vụ.",
      body: "Nạp mượt, rút nhanh, ví điện tử, QR, kênh ngân hàng và tùy chọn crypto — tất cả trong một nền tảng đáng tin cậy. Không thủ công, không chờ đợi.",
      supported: "Hỗ trợ",
      currencies: "Supported currencies",
      currencyCodes: ["PHP", "THB", "VND", "MYR", "MXN", "INR", "USDT"],
      statusLabels: ["Tự Nạp", "Tự Rút", "Xử Lý Nhanh"],
      paymentBodies: [
        "Nạp và rút tức thì qua ví GCash.",
        "Giao dịch liền mạch với hỗ trợ Maya.",
        "Hỗ trợ chuyển khoản ngân hàng qua QRPH toàn quốc.",
      ],
    },
    affiliate: {
      eyebrow: "Chương trình đối tác",
      titleLead: "Mở rộng mạng lưới của bạn,",
      titleAccent: "nhận hoa hồng thật.",
      body: "Trở thành đối tác Alopit và nhận hoa hồng từ doanh thu cược tuyến dưới trên toàn Sabong Arena. Hoa hồng dựa trên doanh thu - mạng lưới của bạn, thu nhập của bạn.",
      tiers: [
        {
          tierLabel: "Gold",
          badge: "Được đề xuất",
          commission: "3%",
          maxLabel: "mức hoa hồng tối đa",
          createdBy: "Chỉ dành cho affiliate Master",
          features: [
            "Hoa hồng dựa trên doanh thu",
            "Ví hoa hồng riêng",
            "Chuyển sang số dư bất cứ lúc nào",
            "Tạo affiliate Silver & Bronze",
            "Nạp/rút đầy đủ cho tuyến dưới",
          ],
        },
        {
          tierLabel: "Silver",
          badge: null,
          commission: "2%",
          maxLabel: "mức hoa hồng tối đa",
          createdBy: "Gold hoặc affiliate Master",
          features: [
            "Hoa hồng dựa trên doanh thu",
            "Ví hoa hồng riêng",
            "Chuyển sang số dư bất cứ lúc nào",
            "Tạo affiliate Bronze",
            "Nạp/rút cho tuyến dưới",
          ],
        },
        {
          tierLabel: "Bronze",
          badge: null,
          commission: "1%",
          maxLabel: "mức hoa hồng tối đa",
          createdBy: "Gold, Silver hoặc affiliate Master",
          features: [
            "Hoa hồng dựa trên doanh thu",
            "Ví hoa hồng riêng",
            "Chuyển sang số dư bất cứ lúc nào",
            "Có thể tạo affiliate tuyến dưới",
            "Nạp/rút cho tuyến dưới",
          ],
        },
      ],
      hierarchyEyebrow: "Thứ bậc tuyển dụng",
      hierarchyNote: "Mỗi cấp có thể tuyển và quản lý các affiliate bên dưới trong chuỗi",
      createdByLabel: "Được tạo bởi:",
      cta: "Trở thành Đối tác",
    },
    beyond: {
      eyebrow: "Ngoài Sabong",
      titleLead: "Thích Alopit?",
      titleAccent: "Hãy thử Alowin.",
      body: "Slot đẳng cấp thế giới, casino trực tiếp và game show - tất cả trên một nền tảng. Trải nghiệm đáng tin cậy như cũ, giải trí không giới hạn.",
      categories: ["Tất cả", "Casino", "Casino Trực tiếp", "Trò chơi"],
      cta: "Khám phá tất cả trò chơi trên Alowin",
      footer: "Slot · Casino Trực tiếp · Bàn cược · Game show",
    },
    sportsbook: {
      eyebrow: "Sportsbook",
      titleLead: "Alowin",
      titleAccent: "Sportsbook.",
      body: "Chuyển giữa thể thao trực tiếp và kèo trước trận cho bóng đá, bóng rổ, tennis và nhiều hơn nữa với cùng trải nghiệm tài khoản Alowin.",
      tags: ["Thể thao trực tiếp", "Trước trận", "Đa môn"],
      boardEyebrow: "Bảng sportsbook",
      boardTitle: "Trực tiếp và trước trận",
      modes: [
        {
          mode: "Trực tiếp",
          title: "Theo dõi diễn biến ngay khi nó xảy ra",
          body: "Vào các trận đang diễn ra và giữ nhịp ngày thi đấu trong trải nghiệm sportsbook của Alowin.",
          cta: "Mở thể thao trực tiếp",
        },
        {
          mode: "Trước trận",
          title: "Lên kế hoạch trước giờ bóng lăn",
          body: "Xem các trận sắp diễn ra, chọn môn thể thao của bạn và vào trước khi trận bắt đầu.",
          cta: "Xem thể thao trước trận",
        },
      ],
      flowEyebrow: "Một luồng sportsbook",
      flowBody: "Bắt đầu với các trận sắp tới, chuyển sang sự kiện trực tiếp, rồi tiếp tục thẳng vào Alowin khi bạn sẵn sàng.",
      cta: "Mở Sportsbook",
    },
    final: {
      eyebrow: "Tham gia ngay",
      titleLead: "Chào mừng đến với",
      titleAccent: "cộng đồng Alopit.",
      body: "Nơi tiện lợi gặp gỡ cộng đồng. Giao dịch tự phục vụ, luồng cao cấp và quyền truy cập độc quyền - tất cả trong một nền tảng.",
      cta: "Bước vào sàn đấu",
      note: "Miễn phí · Web · Không cần tải xuống",
    },
    footer: {
      brand: "Alopit",
      copyright: "© 2026 Alopit",
      responsible: "Chơi có trách nhiệm · 21+",
    },
  },
  es: {
    header: {
      login: "Iniciar sesión",
      register: "Registrarse",
    },
    hero: {
      badge: "Transmisión diaria · Manila",
      titleLead: "Donde el ring",
      titleAccent: "se encuentra con el pulso.",
      body:
        "Transmisiones en vivo originales. Transacciones de autoservicio. GCash, Maya, QRPH: todo en una sola plataforma. Una experiencia premium creada para los fanáticos de sabong que exigen más.",
      cta: "Entrar al ring",
      alt: "Arena de sabong en vivo",
    },
    marquee: [
      "ACCIÓN EN VIVO",
      "PASIÓN REAL",
      "E-SABONG PREMIUM",
      "JUNTO AL RING DESDE CUALQUIER LUGAR",
      "UNA COMUNIDAD",
      "TRANSMISIÓN DIARIA",
      "ALOPIT",
      "MÁS SIMPLE",
      "MÁS CONVENIENTE",
      "TRANSMISIÓN ORIGINAL EN VIVO",
    ],
    trust: [
      {
        title: "Seguro y protegido",
        body: "Acceso confiable a la sala y un sistema sólido.",
      },
      {
        title: "Depósitos y retiros autoservicio",
        body: "Depósitos y retiros rápidos a tu ritmo.",
      },
      {
        title: "Pensado para móvil",
        body: "Diseñado para teléfonos y adaptado con claridad a pantallas más grandes.",
      },
      {
        title: "Soporte en vivo",
        body: "La ayuda está cerca cuando más la necesitas.",
        liveChat: true,
      },
    ],
    promo: {
      ariaPrefix: "Mostrar promoción",
    },
    why: {
      eyebrow: "Por qué Alopit",
      titleLead: "Creado para fanáticos de sabong,",
      titleAccent: "de principio a fin.",
      body: "Transmisiones originales, visualización fluida, transacciones de autoservicio: todo lo que necesitas en una sola plataforma.",
      roomState: "En vivo ahora",
      roomTitle: "Sabong Traditional",
      featureLabel: "Función",
      features: [
        "Transmisión original en vivo",
        "Transacciones de autoservicio",
        "Múltiples canales de pago",
        "Visualización fluida",
        "Comunidad exclusiva",
      ],
      featureBodies: [
        "Transmisiones HD nítidas con baja latencia. No todas las experiencias en vivo son iguales.",
        "Deposita y retira cuando quieras, sin procesos manuales ni esperas.",
        "GCash, Maya y bancos compatibles con QRPH, todo en una sola plataforma.",
        "Un entorno de plataforma dedicado para streaming ininterrumpido.",
        "Invita jugadores, amplía tu red y desbloquea más recompensas juntos.",
      ],
    },
    payments: {
      eyebrow: "La comodidad importa",
      titleLead: "Transacciones",
      titleAccent: "de autoservicio.",
      body: "Depósitos fluidos, retiros rápidos, billeteras, QR, canales bancarios y opciones cripto: todo en una plataforma confiable. Sin procesos manuales, sin esperas.",
      supported: "Disponible",
      currencies: "Supported currencies",
      currencyCodes: ["PHP", "THB", "VND", "MYR", "MXN", "INR", "USDT"],
      statusLabels: ["Depósito propio", "Retiro propio", "Procesamiento rápido"],
      paymentBodies: [
        "Depósitos y retiros instantáneos mediante la billetera GCash.",
        "Transacciones fluidas con soporte de Maya.",
        "Transferencias bancarias por QRPH disponibles en todo el país.",
      ],
    },
    affiliate: {
      eyebrow: "Programa de socios afiliados",
      titleLead: "Haz crecer tu red,",
      titleAccent: "gana comisiones reales.",
      body: "Conviértete en afiliado de Alopit y gana comisiones por el volumen de apuestas de tu red en Sabong Arena. Comisiones basadas en volumen: tu red, tus ganancias.",
      tiers: [
        {
          tierLabel: "Gold",
          badge: "Recomendado",
          commission: "3%",
          maxLabel: "tasa máxima de comisión",
          createdBy: "Solo afiliado Master",
          features: [
            "Comisiones basadas en volumen",
            "Billetera de comisión separada",
            "Transferir al saldo cuando quieras",
            "Crear afiliados Silver y Bronze",
            "Depósito/retiro completo para subredes",
          ],
        },
        {
          tierLabel: "Silver",
          badge: null,
          commission: "2%",
          maxLabel: "tasa máxima de comisión",
          createdBy: "Afiliado Gold o Master",
          features: [
            "Comisiones basadas en volumen",
            "Billetera de comisión separada",
            "Transferir al saldo cuando quieras",
            "Crear afiliados Bronze",
            "Depósito/retiro para subredes",
          ],
        },
        {
          tierLabel: "Bronze",
          badge: null,
          commission: "1%",
          maxLabel: "tasa máxima de comisión",
          createdBy: "Afiliado Gold, Silver o Master",
          features: [
            "Comisiones basadas en volumen",
            "Billetera de comisión separada",
            "Transferir al saldo cuando quieras",
            "Puede crear afiliados de la red descendente",
            "Depósito/retiro para subredes",
          ],
        },
      ],
      hierarchyEyebrow: "Jerarquía de reclutamiento",
      hierarchyNote: "Cada nivel puede reclutar y administrar afiliados por debajo de ellos en la cadena",
      createdByLabel: "Creado por:",
      cta: "Convertirse en afiliado",
    },
    beyond: {
      eyebrow: "Más allá de Sabong",
      titleLead: "¿Te gusta Alopit?",
      titleAccent: "Prueba Alowin.",
      body: "Slots de clase mundial, casino en vivo y game shows: todo en una sola plataforma. La misma experiencia confiable, entretenimiento ilimitado.",
      categories: ["Todo", "Casino", "Casino en vivo", "Juegos"],
      cta: "Explorar todos los juegos en Alowin",
      footer: "Slots · Casino en vivo · Juegos de mesa · Game shows",
    },
    sportsbook: {
      eyebrow: "Sportsbook",
      titleLead: "Alowin",
      titleAccent: "Sportsbook.",
      body: "Muévete entre deportes en vivo y apuestas previas al partido en fútbol, baloncesto, tenis y más con la misma experiencia de cuenta de Alowin.",
      tags: ["Deportes en vivo", "Prepartido", "Multideporte"],
      boardEyebrow: "Panel del sportsbook",
      boardTitle: "En vivo y prepartido",
      modes: [
        {
          mode: "En vivo",
          title: "Sigue la acción mientras sucede",
          body: "Entra a juegos activos y mantén la energía del día del partido dentro de la experiencia de sportsbook de Alowin.",
          cta: "Abrir deportes en vivo",
        },
        {
          mode: "Prepartido",
          title: "Planifica antes del saque inicial",
          body: "Explora los próximos encuentros, elige tu deporte y entra antes de que empiece el juego.",
          cta: "Ver deportes prepartido",
        },
      ],
      flowEyebrow: "Un solo flujo de sportsbook",
      flowBody: "Empieza con los partidos próximos, cambia a eventos en vivo y continúa directo a Alowin cuando estés listo.",
      cta: "Abrir Sportsbook",
    },
    final: {
      eyebrow: "Únete hoy",
      titleLead: "Bienvenido a la",
      titleAccent: "comunidad Alopit.",
      body: "Donde la comodidad se encuentra con la comunidad. Transacciones de autoservicio, transmisiones premium y acceso exclusivo: todo en una sola plataforma.",
      cta: "Entrar a la arena",
      note: "Gratis · Web · Sin descargas",
    },
    footer: {
      brand: "Alopit",
      copyright: "© 2026 Alopit",
      responsible: "Juega con responsabilidad · 21+",
    },
  },
  hi: {
    header: {
      login: "लॉग इन",
      register: "रजिस्टर",
    },
    hero: {
      badge: "रोज़ाना प्रसारण · मनीला",
      titleLead: "जहां रिंग",
      titleAccent: "धड़कन से मिलती है.",
      body:
        "मूल लाइव फीड। सेल्फ-सर्विस ट्रांज़ैक्शन। GCash, Maya, QRPH - सब कुछ एक ही प्लेटफ़ॉर्म पर। यह प्रीमियम अनुभव उन sabong प्रशंसकों के लिए बनाया गया है जिन्हें और चाहिए।",
      cta: "रिंग में कदम रखें",
      alt: "लाइव sabong arena",
    },
    marquee: [
      "लाइव एक्शन",
      "असली जुनून",
      "प्रीमियम ई-साबोंग",
      "कहीं से भी रिंगसाइड",
      "एक समुदाय",
      "रोज़ाना प्रसारण",
      "ALOPIT",
      "ज़्यादा सरल",
      "ज़्यादा सुविधाजनक",
      "मूल लाइव फीड",
    ],
    trust: [
      {
        title: "सुरक्षित और भरोसेमंद",
        body: "विश्वसनीय रूम एंट्री और स्थिर सिस्टम।",
      },
      {
        title: "स्वयं जमा और निकासी",
        body: "तेज़ डिपॉज़िट और विदड्रॉअल, आपके तरीके से।",
      },
      {
        title: "मोबाइल-फर्स्ट",
        body: "फोन के लिए डिज़ाइन किया गया, बड़े स्क्रीन पर भी साफ़।",
      },
      {
        title: "लाइव सपोर्ट",
        body: "जब आपको सबसे ज़्यादा ज़रूरत हो, मदद पास में है।",
        liveChat: true,
      },
    ],
    promo: {
      ariaPrefix: "प्रमोशन दिखाएँ",
    },
    why: {
      eyebrow: "Alopit क्यों",
      titleLead: "sabong प्रशंसकों के लिए बनाया गया,",
      titleAccent: "शुरू से अंत तक.",
      body: "मूल फीड, स्मूद व्यूइंग, सेल्फ-सर्विस ट्रांज़ैक्शन - आपकी ज़रूरत की हर चीज़ एक ही प्लेटफ़ॉर्म में।",
      roomState: "अभी लाइव",
      roomTitle: "Sabong Traditional",
      featureLabel: "फीचर",
      features: [
        "मूल लाइव फीड",
        "सेल्फ-सर्विस ट्रांज़ैक्शन",
        "कई भुगतान चैनल",
        "स्मूद व्यूइंग",
        "एक्सक्लूसिव कम्युनिटी",
      ],
      featureBodies: [
        "क्रिस्टल-क्लियर HD स्ट्रीम, कम लेटेंसी के साथ। हर लाइव व्यू एक जैसा नहीं होता।",
        "कभी भी जमा और निकासी करें - कोई मैन्युअल प्रक्रिया नहीं, कोई इंतज़ार नहीं।",
        "GCash, Maya और QRPH-समर्थित बैंक एक ही प्लेटफ़ॉर्म पर।",
        "बिना रुकावट स्ट्रीमिंग के लिए बनाया गया समर्पित प्लेटफ़ॉर्म वातावरण।",
        "प्लेयर्स को आमंत्रित करें, अपना नेटवर्क बढ़ाएँ, और साथ में ज़्यादा रिवार्ड्स खोलें।",
      ],
    },
    payments: {
      eyebrow: "सुविधा मायने रखती है",
      titleLead: "सेल्फ-सर्विस",
      titleAccent: "ट्रांज़ैक्शन.",
      body: "स्मूद डिपॉज़िट, तेज़ निकासी, वॉलेट, QR, बैंक चैनल और क्रिप्टो विकल्प - सब कुछ एक भरोसेमंद प्लेटफ़ॉर्म में। कोई मैन्युअल प्रक्रिया नहीं, कोई इंतज़ार नहीं।",
      supported: "समर्थित",
      currencies: "Supported currencies",
      currencyCodes: ["PHP", "THB", "VND", "MYR", "MXN", "INR", "USDT"],
      statusLabels: ["स्वयं जमा", "स्वयं निकासी", "तेज़ प्रोसेसिंग"],
      paymentBodies: [
        "GCash वॉलेट से तुरंत जमा और निकासी।",
        "Maya सपोर्ट के साथ आसान ट्रांज़ैक्शन।",
        "देशभर में QRPH-सक्षम बैंक ट्रांसफ़र।",
      ],
    },
    affiliate: {
      eyebrow: "एफ़िलिएट पार्टनर प्रोग्राम",
      titleLead: "अपना नेटवर्क बढ़ाएँ,",
      titleAccent: "असली कमीशन कमाएँ.",
      body: "Alopit के एफ़िलिएट बनें और Sabong Arena में डाउनलाइन बेटिंग टर्नओवर से कमीशन कमाएँ। टर्नओवर-आधारित कमीशन - आपका नेटवर्क, आपकी कमाई।",
      tiers: [
        {
          tierLabel: "Gold",
          badge: "सुझाया गया",
          commission: "3%",
          maxLabel: "अधिकतम कमीशन दर",
          createdBy: "सिर्फ Master affiliate",
          features: [
            "टर्नओवर-आधारित कमीशन",
            "अलग कमीशन वॉलेट",
            "कभी भी बैलेंस में ट्रांसफ़र",
            "Silver और Bronze affiliates बनाएँ",
            "डाउनलाइन के लिए पूरा deposit/withdraw",
          ],
        },
        {
          tierLabel: "Silver",
          badge: null,
          commission: "2%",
          maxLabel: "अधिकतम कमीशन दर",
          createdBy: "Gold या Master affiliate",
          features: [
            "टर्नओवर-आधारित कमीशन",
            "अलग कमीशन वॉलेट",
            "कभी भी बैलेंस में ट्रांसफ़र",
            "Bronze affiliates बनाएँ",
            "डाउनलाइन के लिए deposit/withdraw",
          ],
        },
        {
          tierLabel: "Bronze",
          badge: null,
          commission: "1%",
          maxLabel: "अधिकतम कमीशन दर",
          createdBy: "Gold, Silver, या Master affiliate",
          features: [
            "टर्नओवर-आधारित कमीशन",
            "अलग कमीशन वॉलेट",
            "कभी भी बैलेंस में ट्रांसफ़र",
            "डाउनलाइन affiliate बना सकते हैं",
            "डाउनलाइन के लिए deposit/withdraw",
          ],
        },
      ],
      hierarchyEyebrow: "रिक्रूटमेंट हाइरार्की",
      hierarchyNote: "हर tier अपने नीचे के affiliates को recruit और manage कर सकता है",
      createdByLabel: "द्वारा बनाया गया:",
      cta: "Affiliate बनें",
    },
    beyond: {
      eyebrow: "Sabong से आगे",
      titleLead: "Alopit पसंद है?",
      titleAccent: "Alowin आज़माएँ.",
      body: "वर्ल्ड-क्लास स्लॉट्स, लाइव कैसिनो, और गेम शो - सब कुछ एक ही प्लेटफ़ॉर्म पर। वही भरोसेमंद अनुभव, अनलिमिटेड एंटरटेनमेंट।",
      categories: ["सभी", "कैसिनो", "लाइव कैसिनो", "गेम्स"],
      cta: "Alowin पर सभी गेम्स देखें",
      footer: "स्लॉट्स · लाइव कैसिनो · टेबल गेम्स · गेम शो",
    },
    sportsbook: {
      eyebrow: "स्पोर्ट्सबुक",
      titleLead: "Alowin",
      titleAccent: "Sportsbook.",
      body: "उसी Alowin अकाउंट अनुभव के साथ फ़ुटबॉल, बास्केटबॉल, टेनिस और अन्य खेलों में लाइव स्पोर्ट्स और प्री-मैच एक्शन के बीच जाएँ।",
      tags: ["लाइव स्पोर्ट्स", "प्री-मैच", "मल्टी-स्पोर्ट"],
      boardEyebrow: "स्पोर्ट्सबुक बोर्ड",
      boardTitle: "लाइव और प्री-मैच",
      modes: [
        {
          mode: "लाइव",
          title: "जैसे-जैसे खेल आगे बढ़े, साथ चलें",
          body: "चल रहे खेलों में शामिल हों और Alowin sportsbook अनुभव के भीतर मैचडे ऊर्जा को बनाए रखें।",
          cta: "लाइव स्पोर्ट्स खोलें",
        },
        {
          mode: "प्री-मैच",
          title: "किकऑफ़ से पहले योजना बनाएं",
          body: "आने वाले मैच देखें, अपना खेल चुनें, और शुरू होने से पहले एंटर करें।",
          cta: "प्री-मैच स्पोर्ट्स देखें",
        },
      ],
      flowEyebrow: "एक ही sportsbook फ्लो",
      flowBody: "आने वाले मैचों से शुरू करें, लाइव इवेंट में स्विच करें, और तैयार होने पर सीधे Alowin में जारी रखें।",
      cta: "Sportsbook खोलें",
    },
    final: {
      eyebrow: "आज ही जुड़ें",
      titleLead: "स्वागत है",
      titleAccent: "Alopit समुदाय में.",
      body: "जहाँ सुविधा और समुदाय मिलते हैं। सेल्फ-सर्विस ट्रांज़ैक्शन, प्रीमियम स्ट्रीम, और एक्सक्लूसिव एक्सेस - सब कुछ एक ही प्लेटफ़ॉर्म में।",
      cta: "रिंग में प्रवेश करें",
      note: "मुफ़्त · वेब · डाउनलोड नहीं",
    },
    footer: {
      brand: "Alopit",
      copyright: "© 2026 Alopit",
      responsible: "ज़िम्मेदारी से खेलें · 21+",
    },
  },
} as const;
